### ISSUE TITLE
Create a tile set of 2014 imagery for verification purposes

### ISSUE THREAD

**Issue by tchaddad** [pdxosgeo/pdxbldgimport#17]
Even if we can't have the Metro imagery, we can use the 2014 NAIP.

**Comment by grant-humphries** [comment]
Just a heads up with the meet-up coming this weekend, these haven't been working for me the past couple of days.  Seems like it could be related to the turn of the year.

**Comment by tchaddad** [comment]
Thanks for the heads up - I will follow through with the source to try to see what the problem is...

**Comment by tchaddad** [comment]
So it seems that the old link has transitioned to a more permanent location:

http://gis.apfo.usda.gov/arcgis/services/NAIP/Oregon_2014_1m_NC/ImageServer/WMSServer?service=WMS&request=GetCapabilities

Because this new server is an ESRI ImageServer, and they are just using the default service names*, you need to select the layer named '0' to get the True color layer to display. 

> *Slight side-rant to say that the default service names on ESRI services are 100% horrible, and I don't know how they sleep at night. Aaargghhh!*

All other instructions remain roughly the same. Unfortunately, the CIR version is no longer available from what I can tell. Please test and let me know if there are any JOSM related problems we should sort out before Saturday.

**Comment by grant-humphries** [comment]
Thanks for looking into this Tanya, the new address works no problem for me.  When entering the url into JOSM and clicking 'Get Layers' only one choice comes up which is labeled 'Oregon_2014_1m_Nc' and it's the true color 1 meter imagery.
