### ISSUE TITLE
Data to Import checklist is a little confusing

### ISSUE THREAD

**Issue by tchaddad** [pdxosgeo/pdxbldgimport#26]
One question, one suggestion:
- In the [listing of files] (https://github.com/pdxosgeo/pdxbldgimport/blob/master/data_to_import/Import_Tasks.md), alternating files are listed as "complete" or "in progress", but I don't think this means they have been imported yet. Is it o.k. for me to update that page to remove the confusion?

- I also suggest that as we progress through the import, that we keep the checklist page updated, and add a link to the changest for each file that is processed successfully. This was we can track who has done which files, and it will make it easier to have others check work.

**Comment by darrell** [comment]
Yes, please make it less confusing. The change set thing is a good idea. I would a note to that affect.

We should also add a note specifying what the source comment should be in the change set.

d.

**Comment by geografa** [comment]
@tchaddad some more work here: https://github.com/pdxosgeo/pdxbldgimport/pull/33
