### ISSUE TITLE
address nodes not within buildings

### ISSUE THREAD

**Issue by dobratzp** [pdxosgeo/pdxbldgimport#28]
If you look at 1s1w16c, there are a number of nodes in the 1s1w16c_multi_addr.osm which are not located within buildings in the 1s1w16c.osm file.  See Southwest Hazel Street and Southwest Bonnie Brae Street.

**Comment by darrell** [comment]
This is probably a result of my perturbation function. I'm betting it just nudged the points outside the boundary. I'll try to dig into it.

**Comment by dobratzp** [comment]
It looks like this is fixed when @darrell updated using the latest data in  b17fc3f5c54e109279a04d53e5230658f7d16377.

I'll go through and retry to import the quarter sections that I was having issues with previously.
