### ISSUE TITLE
Error on JOSM import

### ISSUE THREAD

**Issue by geografa** [pdxosgeo/pdxbldgimport#29]
@darrell getting this error on import:

`Could not read file '1n3w25c.osm'. Error is: Line 32 column 71: Attribute name "data-pjax-transient" associated with an element type "meta" must be followed by the ' = ' character.`

Using: 
- Version 8339
- Last change at 2015-05-07 17:30:43 +0200 (Thu, 07 May 2015)
- Java Version 1.8.0_31

Any ideas where to fix this?

**Comment by darrell** [comment]
Huh. I was able to open it just fine with:
Version 8109
Last change at 2015-03-02 00:13:51 +0100 (Mon, 02 Mar 2015)
Java Version 1.7.0_71

Those attributes don't appear in the OSM XML, which makes me think that it's a bug somewhere else..

**Comment by darrell** [comment]
Hey, @dobratzp , I notice in the log files that you're seeing errors. Is it the same one? 

I can open all the files you mentioned using that same version of JOSM just fine.

Which really makes me think this is a JOSM bug.

**Comment by darrell** [comment]
Also, is it possible to coax a stack trace out of JOSM for this?

**Comment by darrell** [comment]
Hmm.. so I was able to open '1n3w25c.osm' just fine with version 8339, but java 1.7.0_71.

@dobratzp what version of java are you running JOSM under?

**Comment by dobratzp** [comment]
I'm running Java 1.8.0_45 and JOSM 8279 on Mac OS X 10.10.3 and I can open the file 1n3w25c.osm in JOSM just fine.

@geografa, the error you are seeing with 1n3w25c.osm seems like the XML parser in JOSM is not considering 1n3w25c.osm to be valid XML.  Can you open other *.osm files from the data_to_import directory?  Can you open the 1n3w25c.osm in a text editor and see if it looks like the other *.osm files?

Also @geografa, how are you launching JOSM?  I typically run it from the command line using:
`java -jar -Xmx2048M josm-tested.jar`
JOSM does print a bunch of things to the console window while it is running, including stack traces when there are errors.  Maybe the console window on your machine can provide additional clues as to what's going wrong.

@darrell, the errors that I mentioned in Issue #28 and also talk about in Import_Tasks.md are all related to problems that I noticed with the data in the files after loading them into JOSM.  I've chosen to skip over those files for now in case we come up with a way to systematically fix the data before importing it.  I've never had any problems actually loading any of the *.osm files in data_to_import in JOSM.

**Comment by Caged** [comment]
@geografa  `data-pjax-transient` is a githubism from the [pjax](https://github.com/defunkt/jquery-pjax) project. Not sure how you're importing the file, but it's possible that you're trying to import a page on github.com instead of the raw contents of a file hosted on GitHub.  You might try to curl down the raw file, which works for me. 

```
curl -O "https://raw.githubusercontent.com/pdxosgeo/pdxbldgimport/master/data_to_import/1n3w25c.osm"
```

**Comment by geografa** [comment]
That was it @Caged . Thanks a ton.
