### ISSUE TITLE
missing buildings in West Linn

### ISSUE THREAD

**Issue by dobratzp** [pdxosgeo/pdxbldgimport#30]
I think I imported the buildings for everything covering parts of West Linn, but it looks like there's a square spot with missing buildings:

http://www.openstreetmap.org/?bbox=-122.6706361771,45.3463394077,-122.6608085632,45.3531857098

I don't believe this area is covered by any of the remaining quarter sections to be imported.  Any idea where these buildings are?

**Comment by darrell** [comment]
It looks like those were in 2s1e34d, which you marked as complete with changeset http://www.openstreetmap.org/changeset/31814797, but that's clearly a different area – actually it looks like that's actually '2s1w34d'. So, small typo.

I've re-added that qtr section to the repo and fixed the Import_Tasks.md

Resolved in 56d6e49559ae7869cbd18488ce2ec53ee9210831 and c5691b8a0a4933286ea4b8834d9fbe75ec823040
