### ISSUE TITLE
Missing blocks?

### ISSUE THREAD

**Issue by tchaddad** [pdxosgeo/pdxbldgimport#31]
I happened to be checking an for a particular block (1s1e18) today, and don't see it listed as "to be done", yet it also clearly has not been done already given a peek at the map. This is probably because it is being held back for some reason (review? conflation?) but I'm curious what the reason might be.

The block in question includes Alpenrose Dairy, which is where I'll be tonight, thus the interest / question...

**Comment by tchaddad** [comment]
Ah wait - might be because it is in the City of Portland? It's right on the Multnomah county, Washington County line...

**Comment by darrell** [comment]
Yah, we've been holding off on the city proper 'til they released their updated address data, but it's looking that will be a while. They're already six months behind!

But, that being said, if there's something you'd like to see in there, I think it's OK to do the import.

**Comment by tchaddad** [comment]
Well unless you happen to have that block handy, I'm unlikely to get to the import today given other stuff, but I may make edits in that block that will need to be conflated later, so that's the (minor) downside of waiting.

**Comment by darrell** [comment]
Well, that's actually a full section, not a quarter section, but I do have it handy. Do you want the whole section?

The conflation won't be an issue, we'll just mark it done in the todo list.

**Comment by ksmpdx** [comment]
If you all are using the Metro (RLIS) address points, those now include the new City of Portland address model and updated address points. It's still being flushed out a bit, and we'll be cleaning it up over the next year or so, but those points are now out in the wild and will continue to be passed on to Metro moving forward.

**Comment by darrell** [comment]
Oh, awesome. I had e-mailed justin but never heard back, and I couldn't find the release notes. Thanks, @ksmpdx. 

I'll start adding them into the Import_Tasks file

**Comment by tchaddad** [comment]
I'd need the SW quarter section, so I guess that would be 1s1e18c

**Comment by geografa** [comment]
@darrell do you have other (quarter) sections in the city available? I've been hesitating to do this outside the city due to lack of knowledge but I feel I could hit some areas close to my hood (NEPO).

**Comment by darrell** [comment]
@tanya, that quarter section has been committed. 

@geografa, I do have the data. Let me add it to repo

**Comment by tchaddad** [comment]
thanks!

**Comment by darrell** [comment]
All Portland data has now been added in 6326f6184c5c. Let the fun begin!

**Comment by geografa** [comment]
:+1: 
![](http://media.giphy.com/media/113ow2SM4jh4nS/giphy.gif)
